###
GET http://localhost:3000/report/income

###
GET http://localhost:3000/report/income/a571ca25-44d2-44d1-9195-d7061c5d24b9

###
POST http://localhost:3000/report/income
Content-Type: application/json

{
  "source": "Udemy",
  "amount": 5000
}

###
PUT http://localhost:3000/report/income/a571ca25-44d2-44d1-9195-d7061c5d24b9
Content-Type: application/json

{
  "source":"asadsadsa",
  "amount": 300
}

###
DELETE http://localhost:3000/report/income/40c4cc20-c7b2-4158-8707-69d694164e12

###
GET http://localhost:3000/summary
